# Custom paths config for main repo
# This config points to the main repo's data and logs directories

# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
project_dir: ${oc.env:PROJECT_DIR}

# path to data directory - pointing to main repo's data directory
data_dir: ${paths.project_dir}/../../data

# path to logging directory - pointing to main repo's logs directory
log_dir: ${paths.project_dir}/../../logs

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd} 