defaults:
  - default.yaml

train:
  dataset:
    _target_: medvae.dataloaders.ConcatDataset
    datasets:
      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/slam.csv
        split_column: split
        split_name: train
        data_dir: ${paths.data_dir}/slam/
        dataset_id: 0
        img_column: image_uuid
        img_suffix: .npy
        quality_column: quality
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: pips.dataloaders.slam_complex_load
              random_flip: true
              rot_degree: 10

      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/slam_dicom.csv
        split_column: split
        split_name: train
        data_dir: ${paths.data_dir}/slam_dicom/
        dataset_id: 1
        img_column: image_uuid
        img_suffix: .npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: pips.dataloaders.slam_dicom_load
              random_flip: true
              rot_degree: 10
  

valid:
  dataset:
    _target_: medvae.dataloaders.ConcatDataset
    datasets:
      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/slam.csv
        split_column: split
        split_name: val
        data_dir: ${paths.data_dir}/slam/
        dataset_id: 7
        img_column: image_uuid
        img_suffix: .npy
        quality_column: quality
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: pips.dataloaders.slam_complex_load

      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/slam_dicom.csv
        split_column: split
        split_name: val
        data_dir: ${paths.data_dir}/slam_dicom/
        dataset_id: 8
        img_column: image_uuid
        img_suffix: .npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: pips.dataloaders.slam_dicom_load

test:
  dataset:
    _target_: medvae.dataloaders.ConcatDataset
    datasets:
      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/slam.csv
        split_column: split
        split_name: test
        data_dir: ${paths.data_dir}/slam/
        dataset_id: 14
        img_column: image_uuid
        img_suffix: .npy
        quality_column: quality
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: pips.dataloaders.slam_complex_load

      - _target_: medvae.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/slam_dicom.csv
        split_column: split
        split_name: test
        data_dir: ${paths.data_dir}/slam_dicom/
        dataset_id: 15
        img_column: image_uuid
        img_suffix: .npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: pips.dataloaders.slam_dicom_load
